// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhnGKIMn3RGlecChJjYNoNpD9QDJ3pMSs',
    appId: '1:161981029365:web:eea54f67501732675bdebc',
    messagingSenderId: '161981029365',
    projectId: 'canteenfinal-48321',
    authDomain: 'canteenfinal-48321.firebaseapp.com',
    storageBucket: 'canteenfinal-48321.firebasestorage.app',
    measurementId: 'G-32RFCPNHPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQG34VAGG5gFHQAOxaiBfpBAq_3Ne8cU',
    appId: '1:161981029365:android:6e3ce29e1c5f44cc5bdebc',
    messagingSenderId: '161981029365',
    projectId: 'canteenfinal-48321',
    storageBucket: 'canteenfinal-48321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOrloOnrTrs5cZwl39Gam1ap1DSlRp8I',
    appId: '1:161981029365:ios:86bb6eb90f5109ad5bdebc',
    messagingSenderId: '161981029365',
    projectId: 'canteenfinal-48321',
    storageBucket: 'canteenfinal-48321.firebasestorage.app',
    iosBundleId: 'com.example.canteenFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOrloOnrTrs5cZwl39Gam1ap1DSlRp8I',
    appId: '1:161981029365:ios:86bb6eb90f5109ad5bdebc',
    messagingSenderId: '161981029365',
    projectId: 'canteenfinal-48321',
    storageBucket: 'canteenfinal-48321.firebasestorage.app',
    iosBundleId: 'com.example.canteenFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhnGKIMn3RGlecChJjYNoNpD9QDJ3pMSs',
    appId: '1:161981029365:web:03a38260d9902e9f5bdebc',
    messagingSenderId: '161981029365',
    projectId: 'canteenfinal-48321',
    authDomain: 'canteenfinal-48321.firebaseapp.com',
    storageBucket: 'canteenfinal-48321.firebasestorage.app',
    measurementId: 'G-JTBXJNGMWK',
  );
}
